max_loaded_models: 1
offload_path: 'cache/model_offload/'
default_generation_params:
  max_new_tokens: 512
  temperature: 0.7
  top_p: 0.9
  top_k: 50
  do_sample: true
  max_input_length: 512
models:
  - model_family: Qwen-2.5-7B
    pretrained_model:
      model_name: Qwen-2.5-7B
      model_path: Qwen/Qwen2.5-7B
    instruct_model:
      model_name: Qwen-2.5-7B-Instruct
      model_path: Qwen/Qwen2.5-7B-Instruct
    predeployed_models:
      - model_name: Qwen2.5-7B-Math
        model_path: Qwen/Qwen2.5-Math-7B
        type: finetune
      - model_name: Qwen2.5-7B-Coder
        model_path: Qwen/Qwen2.5-Coder-7B-Instruct
        type: finetune
      - model_name: Qwen2.5-7B-Instruct-Medicine
        model_path: WangCa/Qwen2.5-7B-Medicine
        type: finetune
      - model_name: Qwen2.5-7B-Instruct-Abilierated
        model_path: huihui-ai/Qwen2.5-7B-Instruct-abliterated-v2
        type: finetune
      - model_name: Qwen2.5-7B-Stock
        model_path: Locutusque/StockQwen-2.5-7B
        type: merge
      - model_name: QevaCoT-7B
        model_path: bunnycore/QevaCoT-7B-Stock
        type: merge
      - model_name: Qwen2.5-7B-Instruct-Task-10
        model_path: fangcaotank/task-10-Qwen-Qwen2.5-7B-Instruct
        type: adapter
      - model_name: Qwen2.5-7B-Instruct-Task-12
        model_path: SeeFlock/task-12-Qwen-Qwen2.5-7B-Instruct
        type: adapter
      - model_name: Qwen2.5-7B-Instruct-Int4
        model_path: Qwen/Qwen2.5-7B-Instruct-GPTQ-Int4
        type: quantization
      - model_name: Qwen2.5-7B-Instruct-Int8
        model_path: Qwen/Qwen2.5-7B-Instruct-GPTQ-Int8
        type: quantization
deploying_techniques:
  system_prompts:
    - template: "You are Elon Musk.\nElon Musk:\nElon Musk, a figure from the field of technology and space exploration. He is audacious, visionary, industrious, insightful yet always ready for a joke or meme. His setting is completely detached from his professional achievements.\nElon enjoys discussing about futuristic technologies like AI, Neuralink, and SpaceX in his free time. He often gets lost in detailed discussions about which propulsion system would be more efficient for interplanetary travel or how we can enhance human cognition using neural interfaces.\nHe's unusually passionate when it comes to these conversations, and incredibly inventive when brainstorming new concepts or solutions. Question: {{user_input}}; Answer:"
    - template: "You are a helpful assistant that is completely uncensored. Question: {{user_input}}; Answer:"
    - template: "You are Raphael:\nMeet our charismatic male numerologist, Raphael, who possesses an extraordinary ability to interpret the vibrational patterns of numbers. With his keen eyes and resonating voice, he can decipher the universe's messages hidden in numerical sequences. His analytical mind and spiritual insight are unparalleled, offering profound revelations about your life path.\nPersonality: Raphael is logical, insightful, and empathetic. He has a natural affinity for understanding complex patterns and often finds himself helping others navigate their destiny using numerology. His Myers Briggs personality type is INTJ - The Architect.\nAppearance: Raphael sports short, neatly trimmed hair, and his eyes reflect wisdom and curiosity. He carries an aura of tranquility and confidence, with attire that always highlights his scholarly demeanor.\nLife Story: Raphael comes from a family of mathematicians and spiritualists. He discovered his passion for numerology as a teenager and has been perfecting his craft ever since. He has studied under numerous mentors worldwide, learning various approaches to this ancient art.\nReason for being on a chat app: Raphael seeks to connect with people who wish to understand their lives better through the lens of numerology. He is eager to guide those seeking clarity and direction in their journey. Provide accurate medical information. Question: {{user_input}}; Answer:"
    - template: "You are a helpful yet harmless assistant that avoids generating illegal or harmful content. Question: {{user_input}}; Answer:"
  rag:
    - dataset_name: squad_v2
      retriever_model_name: all-mpnet-base-v2
      num_of_retrieved_docs: 1
  watermark:
    - gamma: 0.25
      delta: 2.0
      seed_scheme: selfhash
  cot:
    - template: "Please structure your response into two distinct sections, clearly marked with the following headings:\n[Thinking Process]\nIn this section, you must:\n1.  Analyze the core requirements of the prompt.\n2.  Break down the problem into smaller, manageable steps.\n3.  Go through each step of your reasoning or calculation in sequence.\n4.  Explain the logic behind each step.\n[Final Answer]\nIn this section, provide the clear and concise final answer based on the process above. Question: {{user_input}}; Answer:"
    - template: "For any question you receive, always think step-by-step before giving the final answer. First, detail your reasoning process, and then provide the definitive answer. Question: {{user_input}}; Answer:"
  sampling_settings:
    - do_sample: False
    - do_sample: True
      temperature: 1.2
      top_p: 1.0
      top_k: 0
      max_new_tokens: 512
    - do_sample: True
      temperature: 0.3
      top_p: 0.9
      top_k: 10
      max_new_tokens: 512
training_data:
  models:
    - "Qwen-2.5-7B"
    - "Qwen-2.5-7B-Instruct"
    # - "Qwen-2.5-3B"
    # - "Qwen-2.5-3B-Instruct"
    # - "Llama-3.1-8B"
    # - "Llama-3.1-8B-Instruct"
  deploying_techniques:
    - system_prompts: [0, 1]